chapter 9.5 found error (solve it)
run file "debug.txt"
run file
Error: Runtime error:

Caused by:
Cant evaluate a variable without an assigned value!